#+TITLE: Taking a Stand
#+DATE: 2020-11-04

#+STARTUP: showall indent
#+OPTIONS: toc:nil
#+OPTIONS: tex:t

This election cycle has made me see how tribalistic I can be in my perception of
politics. It's very easy for me to fall into a point of view in which there is a "good
team" and a "bad team." This perspective is harmful in that it causes other painful
emotions to arise (e.g. anger), but also in that it prevents me from contributing
meaningfully to the political discourse and being a citizen that contributes to our
country's progress.

For me, the way to alleviate these tribalistic ideas is to replace them with a
meaningful and well-articulated set of ideas and opinions. I think it's time for me to
put myself out there as a person with opinions and ideas on how to improve our country.

So, I'm going to outline my ideas in this post. These views will certainly change over
time, and I hope to become better informed on all of them. That said, I think the
foundational idea of democracy is that aggregating the opinions of many
only-partly-informed citizens is better than only considering the opinions of an
extremely-well-informed elite. So, in that spirit, I will endeavor to articulate my
only-partly-informed viewpoint.

Below, I will state my opinions as fact. I think it makes for a better articulation than
if I'm couching each sentence with "in my opinion..." and "as far as I can see...", but
the reader should be aware that this is implied; I'm far from an expert in most of these
issues, and I am not citing most of my claims. If you think I'm wrong, then I probably
am; please let me know in the comments, preferably with some reference to back up your
correction. I'll happily modify this post as I update my understanding.

* Driving Values

The various positions I take on issues below are all instrumental; that is, they aim to
be in service of certain core values that I hold. It's important to lay these out before
discussing individual points, because they frame any discussions that will be had.

I value *mutual respect and kindness*. I think that society should be built on a
foundation of people respecting one another, and being kind to one another. This doesn't
have to mean that we love one another or even particularly like one another; it just
means that we have to recognize other people as human beings, with wants, hopes, and
lives just as valid as our own.

I care about *liberty*. That is, I want people to have the freedom to do what they want to
do without unreasonable restriction. For example, what religion you practice, who you
choose to have sex with, and what drugs you choose to put in your body should not be
regulated by the government.[fn:liberty]

I care about *economic opportunity*. I want all people in our society to have access to
basic comforts, such as sufficient food, clothing, shelter, and medical care.

I care about *equality*. This goes hand in hand with both liberty and mutual respect. I
think that all people are fundamentally deserving of certain rights, irrespective of
gender, race, intelligence, etc.[fn:equality]

I care about *security*. We should strive to provide a life without unnecessary physical
or psychological dangers.

* Economic Issues

I think economic issues are fundamental. Many of the issues we face as a society are
symptoms of underlying economic issues. If the people in our society felt like
they have economic opportunity, and are confident that their children will have this
opportunity as well, then our society would function much more smoothly.

For exmaple, it seems to me that our nations current drift towards partisan politics and
an anger-driven national discourse is driven by the lack of economic opportunity
available to much of the lower and middle class in American today. We can try and make
changes to the structure of government, or elect different leaders (both of which I
think are good ideas), but ultimately if we do not address the root (economic) causes of
people's discontent, then we will never have a functioning governmental system.

** Education

Education is a huge part of the economic life of an American. A college degree is seen
as crucial to economic success, and various studies have shown that having a bachelor's
degree increases lifetime earnings, with some studies claiming to have established
causality in this relationship.[fn:college-earnings]

But, college is getting more and more expensive, and the marginal value of a college
degree is decreasing as more and more people get them. Now students graduate from
college with five- or six-figure debt, which prevents them from building wealth that can
provide economic security for them as they age and retire.

Bernie Sanders famously campaigned on free college for all. I think *free college is a
bad solution*. It would funnel large amounts of taxpayer money towards colleges that
charge too much and deliver too little in terms of valuable skills. We need to
transition our society away from its obsession with the four-year college degree, and
move towards a trade-school model like [[https://www.bmbf.de/en/the-german-vocational-training-system-2129.html][that implemented in Germany.]]

Some argue that college is about more than just job training; it is about developing
critical thinking skills, and becoming a fully functional citizen. I agree that these
skills are fundamental to civic participation; I don't see most colleges doing an
acceptable job of providing their students with them. For example, the state could run
free community-based classes that teach critical thinking - these would be independent
of whatever vocational training a person decides to undertake.

** Taxation, Spending, & the Social Safety Net

A strong social safety net is an excellent way to prevent economic distress. This will
require more taxes, but this doesn't need to be burdensome on the middle (or even
upper-middle) classes, if done correctly.[fn:taxes]

This social safety net should include expansion of medicare and social
security/welfare. We should provide free childcare for young children, to allow mothers
to participate in the workforce unhindered. I would love to see universal basic income
implemented in an effective way; we would need to significantly increase taxes in order
to do so, however, and probably on more than just the very highest earners, so it's not
obvious to me that it's actually a good idea.

To fund these endeavors, the government needs more revenue. We need to simplify the tax
code, and close loopholes. We need to increase taxes on the very highest earners and
corporations, and enforce the simplified tax code in order to ensure that those taxes
are actually paid. We should also significantly reduce defense spending to free up money
for domestic social spending.[fn:defense]

** Regulation & Deregulation

I think it is an essential role of govenment to regulate certian aspects of the
market. For example, there are shared goods that the market does not incentivize
individual actors to protect, but they are of high value to society as a
whole. Environmental protection regulation is an example of this; I think we need to
implement thorough and carefully thought-out environmental regulation, which expands on
our existing system.

Another key area where the government needs to regulate is in antitrust. The government
should protect and promote a competitive marketplace. The current antitrust law, written
in the era of the railroad barons, is badly outdated and in need of an overhaul in order
to address potential anticompetitive behaviors of modern technology companies.

Conversely, there are many places where the government heavily regulates that inhibit
economic activity and actually prevent the market from creating value. An example of
this is in urban land use; we need less regulation on building and zoning in urban areas
so that builders can generate a supply to meet the growing demand, and undercut the
exploding housing costs in many large American cities. Rent control is _not_ a good
solution for this; it's simply a supply-and-demand problem, and we need to increase the
supply.

** Health Care

Health care should be mentioned, as it related to regulation and deregulation, although
I don't actually have a strong opinion on it. I have heard some solid arguments that the
tangled relationship between US health insurance companies and the health care sector is
a drive of our current explosion in health care costs, and that if we removed some of
the barries put in place then we could have a more efficient market for health care,
that would provide better value.

However, we tend to be bad at even /thinking/ of health care as a good; for example, we
rarely do a cost-benefit consideration of chemotherapy for a loved one, we generally say
"do whatever it takes." For health care to function as a market, we would need to start
considering seriously (for example) whether it's worth $500,000 to extend the life of a
75-year-old by another 8 years.

The opposite end of the spectrum is single-payer healthcare. This might actually be a
good way to get costs down because then the government, as the single customer of
health-care, would have a lot of bargaining power and be able to bring down the price
they pay for services provided. However, if they don't do this effectively, then a _lot_
of taxpayer money would be going to services that may not be worth it (unnecessary
procedures or imaging, for example).

* Governance

The US has a representative government, and we need to make sure that our elected
officials are incentivized to genuinely reflect the views, opinions, and values of the
population that they represent.

I'm going to argue here for changes we should make to our existing system. I will try to
focus on changes that could be enacted legislatively, rather than by constiutional
amendment, because it's very difficult to gather the consensus needed to enact the
latter, particularly in our current political environment.[fn:two-party]

** Campaign Finance Reform

One of the key things that incentivizes elected officials is campaign finance. They need
to please their campaign donors, so that they can raise money to support their
re-election, and election of their party members.

We need to find a way to reduce the amount of money that flows through elections. It is
not always obvious how to make this happen, but one thing that seems clear is that we
should overturn [[https://en.wikipedia.org/wiki/Citizens_United_v._FEC][the Citizens United ruling]] that grants free-speech rights to
corporations, allowing for unchecked corporate political spending. One solution would be
to cap the political donations by individuals & corporations to any campaigns or
political action committees at a relatively small amount (say, $5,000).

This, however, runs into free speech concerns that I'm not entirely settled on;
shouldn't I be able to spend my money on television advertisements saying (within
reason) whatever I like? If I genuinely think that Michael Dukakis is a threat to
American democracy, shouldn't I be able to freely promote that message?

It's not obvious how to handle this, but I think we need to grapple with it in order to
re-establish integrity for our elected officials.

** Legislative Gridlock

Legislative gridlock is a big challenge to progress. It /appears/ that it is more
significant now than it has been in the past, but I'm not certain of that. We have seen
evidence that congress is more polarized, and that there is a trend away from compromise
and towards parties voting as predictable blocks on legislation.[fn:local-national]

This is something we need to address. There may be changes we can make to the
legislative process that encourage compromise, and that would be a positive
step. However, my belief is that this polarization and partisanship ultimately flows
from the people themselves. Politicians are afraid to compromise because they know that
if they work across the aisle, they will be demonized by their constituents and not
re-elected.

One way to reduce polarization is to avoid focus on already-politicized issues. For
example, if Democrats were to relax their traditional position on gun control, then
perhaps they would have more leverage to push for liberal economic policies that would
benefit lower-income Americans. Although some of these policies have been politicized
(e.g. single-payer healthcare) some of them have not, and maintain a fairly bipartisan
support base (e.g. universal basic income).

It's worth noting that we can also sidestep an ineffective legislature by allowing the
private sector to address problems. This will work, sometimes; for example, SpaceX has a
promising new satellite internet technology (Starlink) that I hope will soon provide
broadband internet to any area with a clear view of the sky; this would work around our
nation's embarassingly poor broadband infrastructure (and lack of any political will to
address it). Some problems, however, are not well-addressed by the private sector
(e.g. nature conservation, antitrust law) because market forces work against them.

** Court-Packing

If our legislative branch is not functioning, then the executive and judicial branches
are encouraged to pick up the slack. This has resulted in presidents from Obama onward
severly expanding executive power via executive order, and also a focus on the
appointment of politically-motivated judges as a partisan strategy.

We need to change our system so that it is robust to a partisan judiciary; right now,
and for the foreseeable future, this is the reality of our situation. Assuming the
officials that are empowered to appoint judges are elected fairly,[fn:fair-elections]
then our goal is to ensure that judges are appointed at a roughly consistent rate.

There are a few strategies that would encourage this. One strategy is to have
term-limits in place, rather than the current lifetime appointments. Another is to
increase the size of important courts, most notably the supreme court, so that the churn
of judges happens at a more consistent rate.

Finally, we cannot let the Senate control approval of appointments. The Senate gives
equal voice to _states_, rather than equal voice to individuals. So, it will always be
biased towards the lower-population-density areas, and therefore not be representative
of the will of the people. Such an institution should not hold control over who gets
appointed to the judiciary, especially in our current era of increasing judicial power.

One solution would be to lower the threshold for approval of judges; for example, only
require that 35% approval of judiciary appointments. This, however, has its own
downsides, since it would allow for appointment of even-more-partisan judges to the
bench. I don't know a better solution right now, but I think that it is a problem we
need to address.

** Gerrymandering

Gerrymandering has long been a strategy used to bias legislative bodies. It is
problematic in that it can make that legislative body less representational of the
population, which undermines the fundamental dynamics of democracy that support fair
governance.

In short, we cannot allow the drawing of district lines to be a process controlled by an
inherently partisan legislative body (the state legislatures, in the US). I suspect that
there exist processes that guarantee a fair drawing of district lines; we should codify
those processes into law. Again, this is not something we can leave up to partisan
elected officials; we need to restrict it via a process that disallows such partisan
strategies.

* Social Issues

Social issues are a primary focus of politics in the US, and (from what I can see) are a
major driver of the partisan polarization we see today. They are also touchy, which is
to say that expressing certain opinions on social issues can have severe repurcussions
for people in their personal and professional lives.

Because of that, I am going to refrain from going into much detail on these issues. I am
happy to discuss them in private, but I simply don't trust our current social climate to
handle reasonable, well-thought-out discussion on these issues in the public sphere.

This has been true throughout, but it's worth emphasizing here; these are /just my
opinions/, and I would enjoy the opportunity to change them. If you diagree with me, I
hope you will engage with me so that we can understand one another better, and hopefully
teach eachother a thing or two. I certainly have a lot to learn on all these topics.

** Race & Policing

Racism is a significant issue in America. Slavery is a horrific part of our national
heritage,[fn:wounded-knee] and it reverberates throughout our culture today. We should
always work towards the goal of a society where opportunities (economic, social, etc.)
are not limited by skin color or heritage.

There is a lot of focus lately on the interactions of policing and race. I do support a
restructuring of the America policing system; we give too much authority, and too little
oversight, to police officers. This level of authority and oversight is appropriate when
handling certain issues, but is entirely absurd when (for example) an officer is
handling a routine traffic stop.

A key element of police reform should be a severe reduction in the kinds of situations
that armed police officers handle. Armed officers, like we currently have, generally
have good ability in self-defense and are trained in it, but have very little
social/interpersonal skill, as evidenced by their recent trend of poor decision making
and inability to defuse tense situations that lead to violence and death. Traffic stops,
domestic disputes, etc. should be handled by public servants that have the appropriate
social skills.

That said, I'm not sure that policing is actually the most important driver of racism in
America. Improving economic opportunities for _all_ Americans will go a long way towards
providing opportunities for marginalized groups. Even so, there are attitudes in our
society that will not be addressed simply by economic changes. I don't have a good
answer for that problem, but I do think it is a fundamental one we must tackle if we
wish to function in alignment with the ideal that "all people are created equal."

** Gun Control

The other social issue I will mention is gun control. This is an issue that contributes
_strongly_ to polarization, and prevents liberals from making inroads into rural
communities. I think we should do everything we can to prevent people from having an
unreasonable ability to harm one another. That said, I don't think gun control should be
a high priority.

About 38,000 people have died so far in 2020 due to gun violence. How many of these
would have been prevented if we could outlaw tactical/assault weapons? Only 16,000 of
these weren't suicides, which are generall not done with such weapons. I'd estimate that
outlawing tactical and assault weapons would save fewer than 5,000 lives per year, and I
would guess it would be _much_ fewer, perhaps a reduction of 1,000 lives per year. Compare
that to (for example) obesity, which kills about 300,000 people a year. Smoking kills
over 400,000 people a year.

I think that liberals over-prioritize gun control in their agenda, and it hurts their
ability to enact other, much more important and impactful aspects of their
platform. Frankly, I wish they would give it a rest.

* Conclusion

Again, these things I've been stating as fact are, actually, /just my opinions/. I have
taken up this imperative structure to embody my belief that we can only act from our
current, limited point of view, and that I cannot let the incompleteness of my knowledge
prevent me from having positions and taking action on issues that I see in the world.

The flipside of this is that we always have to be willing to listen, and learn, and
change our opinions. Perhaps (for example) gun violence _is_ one of the most important
social issues facing our society today. I would be interested to see arguments of this,
and I aspire to be open-minded to any arguments that go against my existing
opinions. The things that are inarguable are _values_;[fn:values] those are inherent in
us, and cannot be proven or disproven. As for _how_ we go about enacting those values,
well, that must always be flexible and open to change.

* Footnotes

[fn:equality] This gets complicated, though; what about people in vegitative states?
What about animals? I'm glossing over some nuance here.

[fn:liberty] Of course, there are limits; for example, I believe sex should be performed
only with mutual consent, and young children should be prevented from using certain
drugs.

[fn:college-earnings] I should look up citations for this.

[fn:taxes] This is an area where I am opining without concrete numbers to back it
up. However, most tax analyses are done in a blatantly partisan way; it's very difficult
to find an analysis of taxation and spending that is does not have ulterior
motives. That said, if you have any recommendations, I'd love to hear them.

[fn:defense] Our national security moving forward does not depend on having better
airplanes or tactical equipment; it depends on intelligence and information security
(cybersecurity). I actually think we should invest _more_ heavily in intelligence and
infosec. I wholeheartedly believe that we should support our troops; I think the best
way to do so is to avoid needless conflict, and ensure that these troops have sufficient
economic, social, and medical security when they arrive back home.

[fn:two-party] For example, I think that a two-party system does not necessarily
encourage the best representation, but this is so baked in to how our voting systems
work that I don't really discuss it here. In that particular case, I also am not really
confident that a many-party system (a la Israel) is actually more effective or
representative.

[fn:local-national] Vox recently [[https://www.vox.com/polyarchy/2018/5/31/17406590/local-national-political-institutions-polarization-federalism][wrote an interesting article]] on how our polarization
may result from the fact that our system was designed for local political institutions,
but most people now focus primarily on national politics.

[fn:fair-elections] It is my opinion that this is _not_ currently the case, due to
e.g. gerrymandering of congressional districts.

[fn:wounded-knee] I would be remiss to not also mention the other horrifici aspect of
our national heritage: the systematic extermination of the indigenous peoples that
inhabited North America previous to the arrival of Europeans. For a heartbreaking
account of this, I recommend [[https://www.amazon.com/Bury-My-Heart-Wounded-Knee/dp/0099526409/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=][Bury My Heart at Wonded Knee]] by Dee Alexander Brown.

[fn:values] Values can change, of course, but they are not subject to evidence in the
same way that strategies are. I cannot prove to you that (for example) freedom is more
important than security; it is simply an opinion that one holds. That said, if we spend
time with one another, and maintain an open-minded attitude, then we tend to absorb one
another's values, which is a process that leads us towards a more harmonious society.
