#+TITLE: It's Been a While...
#+DATE: 2023-08-07

#+STARTUP: showall indent
#+OPTIONS: toc:nil
#+OPTIONS: tex:t

Since the last time I wrote on this site, a lot has changed. A global pandemic has come
and (mostly) gone, which has given rise to remote work as a viable option for many in
the tech sector, but also pushed forward an economic chain of events that made it harder
for companies to get easy funding without demonstrating strong fiscal
responsibility.[fn:1] The industry looks very different today than it did back in
September of 2019, when I wrote my last post.

What have I been up to in that time? I spend the beginning of the pandemic working
remotely for Stitch Fix. During this time, my partner and I moved around the country,
spending a month or two in various places in California, Washington, and finally near my
childhood home in western New York State. Experiencing the support of being near my
family and dear friends of decades, as well as the newfound viability of a remote-first
career, led us to purchase a home in [[https://ecovillageithaca.org/][the Ecovillage at Ithaca]]. We've been living here
for over a year now, and it's been food for my soul to be near my people and live closer
to the land. Swimming in the pond, sweating in the sauna in winter, swimming in the
gorges in the summer, sharing meals with the community, going on night walks surrounded
by fireflies; it really is a magical place.

Around the time I moved to Ithaca, I also left Stitch Fix to start a new job as Senior
ML Engineer with [[https://abnormalsecurity.com/][Abnormal Security]]. I enjoyed the high-impact nature of the role, and
the dynamic character of the organization, but after a year I was feeling really burned
out, and realized I needed some time to myself. Over the last three months I've taken
time meditate, ride my bicycle, and reflect on where I want to go next in my career.

That reflection has coincided with one of the hottest summers on record. Sea ice in the
Southern hemisphere is at a record low, and wildfires raging in Canadian forests have
frequently blanketed the Eastern US in dangerous levels of smoke. It is now glaringly
apparent that there is nowhere we can go to escape the impact of climate change - it
will have effects everywhere in the world, even in places like Ithaca that are better
insulated against the (local) effects.

Seeing this, and feeling the direct impact it has on my life, I think I need to try and
do what I can to contribute. As the summer winds down, I feel ready to dive back into
the professional world. To that end, I'm looking for a Senior ML/DS role in an
organization that is working to mitigate climate change.

If you think you have an opening where I could be a good fit, or would just like to
connect, don't hesitate to reach out! My email is [[mailto:peter@pwills.com][peter@pwills.com]] and I'm happy to put
some time on the calendar to chat.

To the next adventure!

* Footnotes

[fn:1] The Federal Reserve has increased interest rates in order to combat
inflation. From [[https://www.bls.gov/opub/mlr/2023/beyond-bls/what-caused-inflation-to-spike-after-2020.htm][this study on the sources of inflation]] by the US Bureau of Labor
Statistics: "So, from this research, the authors find that three main components explain
the rise in inflation since 2020: volatility of energy prices, backlogs of work orders
for goods and service caused by supply chain issues due to COVID-19, and price changes
in the auto-related industries."
