// This file is auto-generated by scripts/generate-file-structure.js
// Do not edit manually - run 'npm run generate-files' to update

export const fileStructure = {
  "terminal": "terminal",
  "resume.pdf": "/resources/resume.pdf",
  "ds-study-guide": {
    "eng.md": "/resources/ds-study-guide/eng.md",
    "ml.md": "/resources/ds-study-guide/ml.md",
    "stats.md": "/resources/ds-study-guide/stats.md"
  },
  "writing": {
    "blogging-in-org.md": "/resources/writing/blogging-in-org.md",
    "entropy.md": "/resources/writing/entropy.md",
    "types-as-propositions.md": "/resources/writing/types-as-propositions.md",
    "your-p-values-are-bogus.md": "/resources/writing/your-p-values-are-bogus.md"
  }
};

export const defaultExpandedFolders = [
  "ds-study-guide",
  "writing"
];
